package edu.stanford.cfuller.analysistoolsinterface

import javax.swing.GroupLayout
import javax.swing.LayoutStyle

/**

 * @author cfuller
 */
class MaximumIntensityProjectionWindow
/** Creates new form MaximumIntensityProjectionWindow  */
(internal var controller: MaximumIntensityProjectionController) : javax.swing.JFrame() {

    init {
        initComponents()
    }

    var directoryText: String
        get() = this.directoryTextField!!.text
        set(newText) {
            this.directoryTextField!!.text = newText
        }

    var status: String
        get() = this.statusLabel!!.text
        set(status) {
            this.statusLabel!!.text = status
        }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    fun initComponents() {

        jLabel1 = javax.swing.JLabel()
        directoryTextField = javax.swing.JTextField()
        jLabel2 = javax.swing.JLabel()
        browseButton = javax.swing.JButton()
        goButton = javax.swing.JButton()
        jLabel3 = javax.swing.JLabel()
        statusLabel = javax.swing.JLabel()

        defaultCloseOperation = javax.swing.WindowConstants.DISPOSE_ON_CLOSE

        jLabel1!!.font = java.awt.Font("Lucida Grande", 0, 14) // NOI18N
        jLabel1!!.text = "Make Maximum Intensity Projections"

        jLabel2!!.text = "File or directory to process:"

        browseButton!!.text = "Browse"
        browseButton!!.addActionListener { evt -> browseButtonActionPerformed(evt) }

        goButton!!.text = "Go"
        goButton!!.addActionListener { evt -> goButtonActionPerformed(evt) }

        jLabel3!!.text = "Status: "

        statusLabel!!.text = "Ready"

        val layout = GroupLayout(contentPane)
        contentPane.layout = layout
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(directoryTextField!!, GroupLayout.PREFERRED_SIZE, 333, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(browseButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(goButton)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(statusLabel)))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, java.lang.Short.MAX_VALUE.toInt()))
        )
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel2)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(directoryTextField!!, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(browseButton)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(goButton)
                                        .addComponent(jLabel3)
                                        .addComponent(statusLabel))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, java.lang.Short.MAX_VALUE.toInt()))
        )

        pack()
    }// </editor-fold>//GEN-END:initComponents

    private fun browseButtonActionPerformed(evt: java.awt.event.ActionEvent) {//GEN-FIRST:event_browseButtonActionPerformed
        controller.browseButtonPressed()
    }//GEN-LAST:event_browseButtonActionPerformed

    private fun goButtonActionPerformed(evt: java.awt.event.ActionEvent) {//GEN-FIRST:event_goButtonActionPerformed
        controller.goButtonPressed()
    }//GEN-LAST:event_goButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private var browseButton: javax.swing.JButton? = null
    private var directoryTextField: javax.swing.JTextField? = null
    private var goButton: javax.swing.JButton? = null
    private var jLabel1: javax.swing.JLabel? = null
    private var jLabel2: javax.swing.JLabel? = null
    private var jLabel3: javax.swing.JLabel? = null
    private var statusLabel: javax.swing.JLabel? = null

    companion object {

        internal val serialVersionUID = 1L
    }
    // End of variables declaration//GEN-END:variables

}
